---
name: conan-package

# Exports the recipe, sources and binaries for Mac, Windows and Linux and upload these to the server such that these can
# be used downstream.
#
# It should run on pushes against main or CURA-* branches, but it will only create the binaries for main and release branches

on:
  workflow_dispatch:
    inputs:
      create_binaries_windows:
        required: true
        default: false
        description: 'create binaries Windows'
      create_binaries_linux:
        required: true
        default: false
        description: 'create binaries Linux'
      create_binaries_macos:
        required: true
        default: false
        description: 'create binaries Macos'

  push:
    paths:
      - 'plugins/**'
      - 'resources/**'
      - 'cura/**'
      - 'icons/**'
      - 'tests/**'
      - 'packaging/**'
      - '.github/workflows/conan-*.yml'
      - '.github/workflows/notify.yml'
      - '.github/workflows/requirements-conan-package.txt'
      - 'requirements*.txt'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'GitVersion.yml'
      - '*.jinja'
    branches:
      - main
      - 'CURA-*'
      - '[1-9].[0-9]'
      - '[1-9].[0-9][0-9]'
    tags:
      - '[1-9].[0-9].[0-9]*'
      - '[1-9].[0-9].[0-9]'
      - '[1-9].[0-9][0-9].[0-9]*'

env:
  CONAN_LOGIN_USERNAME_CURA: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD_CURA: ${{ secrets.CONAN_PASS }}

# FIXME: point to `main` once merged
jobs:
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-10831
    with:
      project_name: cura

  conan-package-export:
    needs: [ conan-recipe-version ]
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-export.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
    secrets: inherit

  conan-package-create-linux:
    needs: [ conan-recipe-version, conan-package-export ]

    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-linux.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      conan_extra_args: '-c tools.build:skip_test=True -o ${{ needs.conan-recipe-version.outputs.project_name }}:enable_i18n=True'
    secrets: inherit
