name: Get Conan Recipe Version

on:
    workflow_call:
        inputs:
            project_name:
                required: true
                type: string

        outputs:
            recipe_id_full:
                description: "The full Conan recipe id: <name>/<version>@<user>/<channel>"
                value: ${{ jobs.get-semver.outputs.recipe_id_full }}

            recipe_id_latest:
                description: "The full Conan recipe aliased (latest) id: <name>/(latest)@<user>/<channel>"
                value: ${{ jobs.get-semver.outputs.recipe_id_latest }}

            recipe_semver_full:
                description: "The full semver <Major>.<Minor>.<Patch>-<PreReleaseTag>+<BuildMetaData>"
                value: ${{ jobs.get-semver.outputs.semver_full }}

jobs:
    get-semver:

        runs-on: ubuntu-latest

        outputs:
            recipe_id_full: ${{ inputs.project_name }}/${{ steps.git-tool.outputs.Major }}.${{ steps.git-tool.outputs.Minor }}.${{ steps.git-tool.outputs.Patch }}-${{ steps.git-tool.outputs.PreReleaseTag }}+${{ steps.git-tool.outputs.BuildMetaData }}@${{ steps.get-conan-broadcast-data.outputs.user }}/${{ steps.get-conan-broadcast-data.outputs.channel }}
            recipe_id_latest: ${{ steps.latest-alias.outputs.recipe_id_latest }}
            semver_full: ${{ steps.git-tool.outputs.Major }}.${{ steps.git-tool.outputs.Minor }}.${{ steps.git-tool.outputs.Patch }}-${{ ssteps.git-tool.outputs.PreReleaseTag }}+${{ steps.git-tool.outputs.BuildMetaData }}
            user: ${{ steps.get-conan-broadcast-data.outputs.user }}
            channel: ${{ steps.get-conan-broadcast-data.outputs.channel }}

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}
                    fetch-depth: 0

            -   name: Install GitVersion
                uses: gittools/actions/gitversion/setup@v0.9.13
                with:
                    versionSpec: '5.x'

            -   name: GitTools
                id: git-tool
                uses: gittools/actions/gitversion/execute@v0.9.13

            -   id: get-conan-broadcast-data
                name: Get Conan broadcast data
                run: |
                    if [ "${{ github.ref_type == 'tag' }}" = "true" ]; then
                      echo '::set-output name=user::_'
                      echo '::set-output name=channel::_'
                    elif [ "${{ github.ref_name == 'main' || github.ref_name == '5.1' }}" = "true" ]; then
                      # FIXME: For release branches
                      echo ${{ github.repository_owner }} | awk '{print "::set-output name=user::"tolower($0)}'
                      echo '::set-output name=channel::stable'
                    else
                      echo ${{ github.repository_owner }} | awk '{print "::set-output name=user::"tolower($0)}'
                    
                      branch=${{ github.ref_name }}
                      sanitized_branch="${branch//-/_}"
                    
                      if [ "${{ github.event_name == 'merge' }}" = "true" ]; then
                            echo $sanitized_branch | awk '{print "::set-output name=channel::m_"substr(tolower($0),0,9)}'
                      elif [ "${{ github.event_name == 'pull_request' }}" = "true" ]; then
                            echo $sanitized_branch | awk '{print "::set-output name=channel::pr_"substr(tolower($0),0,9)}'
                      else
                        echo $sanitized_branch | awk '{print "::set-output name=channel::"substr(tolower($0),0,9)}'
                      fi
                    fi

            -   name: Get latest alias
                id: latest-alias
                run: |
                    # FIXME: Remove the CURA-9365 clause once merged to main
                    if [ "${{ github.ref_name == 'main' }}" = "true" || "${{ contains(github.ref_name, 'CURA-9365') }}" ]; then
                      echo "::set-output name=recipe_id_latest::${{ inputs.project_name }}/latest@${{ steps.get-conan-broadcast-data.outputs.user }}/${{ steps.get-conan-broadcast-data.outputs.channel }}"
                    else
                      echo "::set-output name=recipe_id_latest::''"
                    fi
