name: conan-package

on:
  push:
    paths:
      - 'plugins/**'
      - 'cura/**'
      - 'resources/bundled_packages/**'
      - 'resources/i18n/**'
      - 'resources/qml/**'
      - 'resources/setting_visibility/**'
      - 'resources/shaders/**'
      - 'resources/texts/**'
      - 'resources/themes/**'
      - 'resources/public_key.pem'
      - 'resources/README_resources.txt'
      - 'icons/**'
      - 'tests/**'
      - 'packaging/**'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/notify.yml'
      - '.github/workflows/requirements-runner.txt'
      - 'requirements*.txt'
      - 'conanfile.py'
      - 'conandata.yml'
      - '*.jinja'
    branches:
      - 'main'
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
# FIXME: Use main once merged
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@CURA-11622_conan_v2
    with:
      project_name: cura
      platform_windows: false
      platform_mac: false
    secrets: inherit
