name: process-pull-request

on:
  pull_request_target:
    branches:
      - "process-pull-request_Add_label_permissions"
    types: [ opened, reopened, edited, review_requested, ready_for_review, assigned ]

jobs:
  add_label:
    uses: ultimaker/cura-workflows/.github/workflows/process-pull-request.yml@workflow_add_label_to_PR_permission
    secrets: inherit
    permissions: inherit
